tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "asdf"
brew "awscli"
brew "bat"
brew "direnv"
brew "fish"
brew "fzf"
brew "ghq"
brew "gibo"
brew "git"
brew "gnupg"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "lft"
brew "mas"
brew "pinentry-mac"
brew "thefuck"
brew "tree"
brew "watchman"
brew "yarn"
brew "github/gh/gh"
cask "1password"
cask "alfred"
cask "amazon-music"
cask "android-studio"
cask "authy"
cask "bartender"
cask "bettertouchtool"
cask "brave-browser"
cask "carbon-copy-cloner"
cask "daisydisk"
cask "docker"
cask "dropbox"
cask "flux"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "google-chrome"
cask "google-japanese-ime"
cask "gyazo"
cask "iterm2"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "kindle"
cask "malwarebytes"
cask "notion"
cask "parallels"
cask "slack"
cask "steam"
cask "spotify"
cask "the-unarchiver"
cask "timemachineeditor"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "zoomus"
cask "betterzip"
cask "font-fira-code"
cask "keycastr"
cask "ngrok"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "suspicious-package"
cask "homebrew/cask-versions/firefox-developer-edition"
cask "homebrew/cask-drivers/logitech-options"
mas "bz.tida.MacWinZipperLite", id: 414855915
mas "com.apple.dt.Xcode", id: 497799835
mas "com.apple.garageband", id: 408980954
mas "com.apple.iMovieApp", id: 408981434
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.apple.iWork.Numbers", id: 409203825
mas "com.apple.iWork.Pages", id: 409201541
mas "com.blackmagic-design.DiskSpeedTest", id: 425264550
mas "com.helloresolven.GIF-Brewery-3", id: 1081413713
mas "com.littlehj.Pixave", id: 924891282
mas "com.microsoft.to-do-mac", id: 1274495053
mas "com.mizage.Divvy", id: 413857545
mas "com.pilotmoon.popclip", id: 445189367
mas "signal", id: 525912054
