tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "asdf"
brew "awscli"
brew "bat"
brew "cocoapods"
brew "direnv"
brew "fish"
brew "fzf"
brew "gh"
brew "ghq"
brew "gibo"
brew "git"
brew "gnupg"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "lft"
brew "mas"
brew "ncdu"
brew "pinentry-mac"
brew "thefuck"
brew "tree"
brew "watchman"
brew "yarn"
cask "1password"
cask "alfred"
cask "amazon-music"
cask "android-studio"
cask "authy"
cask "bartender"
cask "bettertouchtool"
cask "betterzip"
cask "brave-browser"
cask "carbon-copy-cloner"
cask "daisydisk"
cask "docker"
cask "dropbox"
cask "firefox-developer-edition"
cask "flux"
cask "font-fira-code"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "google-chrome"
cask "google-japanese-ime"
cask "gyazo"
cask "iterm2"
cask "karabiner-elements"
cask "keyboardcleantool"
cask "keycastr"
cask "kindle"
cask "logitech-options"
cask "malwarebytes"
cask "ngrok"
cask "notion"
cask "parallels"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "slack"
cask "spotify"
cask "steam"
cask "suspicious-package"
cask "the-unarchiver"
cask "timemachineeditor"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "zoomus"
mas "Disk Speed Test", id: 425264550
mas "Divvy", id: 413857545
mas "GarageBand", id: 408980954
mas "GarageBand", id: 682658836
mas "GIF Brewery 3", id: 1081413713
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Microsoft To Do", id: 1274495053
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixave", id: 924891282
mas "PopClip", id: 445189367
mas "WiFi Signal", id: 525912054
mas "WinArchiver Lite", id: 414855915
mas "Xcode", id: 497799835
