# fnox shell wrappers — generated by bin/install-fnox-shell-wrappers (edit the TOOLS list there).
# Route package managers through `fnox exec` (registry token injected per-invocation).
# Bypass with `command <tool>`. Version resolution / install is delegated to mise.
function npm; fnox exec -- npm $argv; end
function npx; fnox exec -- npx $argv; end
function yarn; fnox exec -- yarn $argv; end
function bun; fnox exec -- bun $argv; end
function bunx; fnox exec -- bunx $argv; end
function pnpm; fnox exec -- pnpm $argv; end
function pnpx; fnox exec -- pnpx $argv; end
